### ISSUE TITLE
Accidentally opening task edit mode is too easy - make checkbox, +/-, and checklist icons larger?

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#236]
From [email](https://mail.google.com/mail/u/0/#inbox/15197f914e3ed98d):

"**it's way too easy to get into edit mode (a vast expanse in the center), and therefore somewhat difficult to check things off or open a checklist. Maybe expand the side portions a little?**"

This has also been noticed by Alys and redphoenix.

Related: https://github.com/HabitRPG/habitrpg-android/issues/213 "Habit +/- buttons are easy to misclick - add option to separate them to opposite sides of the screen"

**Comment by benjwrdill** [comment]
Making quick press anywhere on the list item check off a task and using a long press to edit would work.

**Comment by vIiRuS** [comment]
As the long press would have poor discoverability (users can easily forget how to edit or never find it), i'd prefer to not do it that way.
The problem here is that the checkbox doesn't span the whole left part of the row. If that were the case, the tap area for checking would be much larger and you wouldn't accodentally start editing
