### ISSUE TITLE
Use Kotlin as language

### ISSUE THREAD

**Issue by porokoro** [HabitRPG/habitrpg-android#260]
User ID: 11b5323f-c64c-4d25-a09e-0643c580b5db

I already discussed with @negue about considering to use Kotlin as programming language in this project and as this project is open source now I would like to ask to all contributors. And I simply wanted to ask you before I start opening pull requests that use this language. I personally use this language quite a while now and can really recommend it. Though it is in beta stage it is already **production ready** (full release comes soon).

Currently this language contains a lot of features that are missed in Java. My favorite features are:
- Null safety
- Lambdas
- Smart casts
- Extension functions

In addition it's **100% Java compatible** because it compiles down to Java bytecode in the end. You can use Java code in Kotlin an vice versa. Thus the source could be converted step by step.
Despite the fact that this language has some differences, it is still quite easy to learn if you are familiar with Java.

For more information about the language read [this](http://kotlinlang.org/).

**Comment by ianrumac** [comment]
Hi @porokoro , 
I agree with you that Kotlin is awesome and also use it daily, but I wonder if it's suitable for a project like this, since it might put off a number of people from contributing - even tho interoperability with Java works perfectly, the community is still small compared to Java. IMO, I'd propose to use it in utilities classes and tests at first and later on, when the application is more stable and has increased test coverage start writing other parts in it. 

Also, for those that have more questions about the language, you can join us in official slack group at 
[KotlinLang slack](http://kotlinslackin.herokuapp.com/).
