### ISSUE TITLE
Collection Quests without images have a blank space

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-android#296]
![screenshot_2015-12-13-08-44-47](https://cloud.githubusercontent.com/assets/3494081/11834412/0c40b984-a381-11e5-821c-7f58d1794b94.png)
Collection Quests that don't have images have a blank space. We're working on art for these quests, but that will take a long time, so perhaps in the meantime the image of the item being collected could work instead?

**Comment by Alys** [comment]
This is happening because on the website, we put in blank images for quests that were missing them to allow correct formatting in the quest box. From a technical point of view, the quest does have an image; it's just one that's blank.

ref: https://github.com/HabitRPG/habitrpg/issues/4936
in particular: https://github.com/HabitRPG/habitrpg/issues/4936#issuecomment-123667548

**Comment by Alys** [comment]
And an alternative workaround was suggested here: https://github.com/HabitRPG/habitrpg/issues/4936#issuecomment-123513894
It might be time to do that on the website now instead of the current workaround.
