### ISSUE TITLE
App is killing me?

### ISSUE THREAD

**Issue by leoboiko** [HabitRPG/habitrpg-android#327]
The following has happened to me twice:

- I completed all dailies before my cron time (which is set to 4h, local time)
- I open the Habitica Android app
- "You died" message

Today I managed to confirm that I was alive and with streaks intact in the website; then I opened the app, died, opened the site, all streaks gone.

**Comment by Alys** [comment]
@leoboiko This might actually be caused by a problem on the website where your actions to mark the Dailies as completed are not being correctly recorded.

Please see this issue: https://github.com/HabitRPG/habitrpg/issues/4313
Some parts of it might not seem relevant, but if you are dying even when all your Dailies are complete, there's a good chance it's causing the death. That issue is that your browser's local storage is holding on to changes that you make instead of sending them to the Habitica server to be permanently saved, so it looks on your browser as if you've done your Dailies, but when you access the server through the app, the app thinks that you have not. (A secondary part of the issue is that your browser later does send your actions to the server, making your Dailies appear complete again after you've died, but that part doesn't always happen.)

The only section in that issue that you need to read is the "Advice" section near the top, in particular points 2, 3, and 4. The information in point 4 about the Data Display Tool is especially useful because that tool will tell you if the Habitica server does know whether your Dailies have been completed. You should use that tool before your Custom Day Start time to check whether your Dailies are all done.

**Comment by leoboiko** [comment]
That may well be it, yeah, especially since I'm on a mobile connection. I'll check with the data tool next time, and if I can observe the behavior using only the website, we can close this. Thank you for guidance!

**Comment by leoboiko** [comment]
It really appears to be #4313. Sorry!

**Comment by Alys** [comment]
Thank you for letting us know! We're sorry that bug is troubling you!
