### ISSUE TITLE
loss of hp after signing in during the day

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitrpg-android#450]
I have Samsung Galaxy note and changed over to Galaxy S7 edge. I logged out of my mobile app and my mobile browser(chrome which was updated) my hp was at 50 and I do not use my computer, except to write up this report. I was logged out for 3 hours, all during the day, my dailies were halfway checked off, when I logged back in my hp dropped down to 15% but the dailies that I checked off remained checked off, yes i did refresh multiple times...this was a few days ago, today I noticed that all my streaks were reset to 1 and I manually changed them over. The problem I noticed was this only happens when I  log out of the app and mobile browser.
android Marshmallow version (now) but occurred on my Note 4 as well
during the day
not in a quest
user:   
I did not clear my cache since I was going to download the app to my new phone and I didn't want to loose any info.
hope I gave you all the info you need
thank you 
Mary

**Comment by Alys** [comment]
JerseyEmerald's User ID is 29c5340b-d150-4347-862c-fec571a18b8a (the User ID above isn't quite right). She's JerseyGirl in Habitica.

Here's an earlier conversation from the Tavern:

_JerseyEmerald wrote:_

"I think I might have figured out a problem involving loosing hp when all the dailies are completed..if I log out of my app, my mobile browser and computer for the night, when I sign in I lost most of my hp...however, if I keep my mobile app signed in, my hp remains full...does anyone else have the same issue????

"I keep my mobile app signed in but I'm still logged out on my mobile browser and computer, my xp remains full

"Part 3..I wasn't in a quest when I logged out in all 3 locations

"Ok, here's my problem that I didn't notice until a few min ago, some how all my dailes have been reset back to 1 but they still have the same date from when I originally added them..... it shows streak 1>>upload,edit,delete how can I change it back

"I'm talking about the streak counter at the top of each daily.."


_I wrote:_

"The missing streaks and the health problem you reported from a couple of hours ago are from this bug: https://github.com/HabitRPG/habitrpg/issues/4313 . Your browser is displaying the results of your actions to mark your Dailies as completed but it's not sending those actions to the server for permanent storage, so when cron runs, it thinks you didn't complete your Dailies and sets their streaks to zero and takes away your health. Sometimes the browser will then send your actions to the server after that has happened, which means the Dailies become completed immediately after cron and gain a streak of one. That issue has an "Advice" section near the top which will help you recover from the unfair damage and might help you recognise and avoid the problem if it keeps happening."


_JerseyEmerald wrote:_

"Thank you for the information, however, I don't use a computer, I use my mobile app and mobile browser. I go to my mobile browser, check off all my items there, then i go to my mobile app, sync data, and recheck both to make sure they are marked completed on both sides which it shows they are. I only encounter a problem when i log out of both mobile app and mobile browser.After I sign back in that's when I have that problem so I stopped logging out. Im going to tread up on the information you sent me though, thank you for that."

**Comment by Alys** [comment]
Also, her Custom Day Start time is midnight. Her party hasn't been on a boss quest since at least 2016-03-02 13:00.

@JerseyEmerald some questions that might help us work out what's going on:

1. You said that when you log out of the app and the website, you lose health. How many times did you notice that happening? Have you ever logged out and NOT lost health unexpectedly?

2. In the Tavern you said that you logged out for the night. Do you remember what day that was? When you signed in after that, was it the next morning? Or was it later that night but before midnight?

3. In the issue here, you said you were logged out for 3 hours, all during the day. So that's a different instance of this bug than the one from the Tavern? Do you remember what day that was? When you logged back in after those 3 hours, was it still the same day? Or was it after midnight?

4. Do you do a lot of clicks on the negative buttons for Habits? I.e., roughly how much health would you lose each day from negative Habits?

**Comment by JerseyEmerald** [comment]
The first time it happened was a while ago, I always log out of my apps on my phone as well as any mobile browsers and my computer. I figured I was new and did something wrong. So I let it go. I was alone and not in a team yet.

 The 2nd time was on maybe Wednesday/Thursday, I logged off mobile app and my mobile browser during the day for about 3 hrs or so, I believe it was around 2 pm and logged back in around 5 or 6 pm the same day, my team wasn't in a quest at that time, I did not use my computer until today to write up this problem. 
no negative habits
when i signed out I had 50 hp, 
after a few hrs i signed back in, my hp was 15%
I only noticed my dailies streak was at 1 and that was today...I didn't keep track of my gold and I have so much armor if I lost any I didn't notice 
so I stayed signed in since then and I'm in a quest now but no problems other then the streak issue, and loss of hp when i logged out/in.... I guess I need to add how to be more observant to my list of to do's
No I have not tried to log out since a few days back, I was concerned that I might encounter the problem again. Should I try to log out and see what happens??
Thanks again, sorry about this issue.
Mary

**Comment by Alys** [comment]
No worries - logging an issue is the correct thing to do when you think you've experienced a bug!

Since it's happened only twice, I'd say that logging out was coincidental. Also there's nothing I can think of that can break from logging out. It's safe for you to log out whenever you wish.

I've checked your account and you haven't lost any equipment. If you had, it would be visible in the Rewards column on the task page on the website, and also in the Rewards column on the app. This means that you haven't died from health loss.

Loosing streaks as you described is almost certainly from the bug I described in the Tavern (https://github.com/HabitRPG/habitrpg/issues/4313 ). The health loss probably is too. It's odd that you seemed to loose health in the middle of the day, but there might have been some odd caching or syncing problem happening. I don't think we'd be able to investigate it now that a few days have passed. 

The best advice that I can give you for now is to keep checking that those Dailies which you've marked as completed do still appear completed on both the website and app after you've synced on both.

To-Dos can never hurt you under any circumstances so you don't need to pay close attention to them.

Let us know if the problem happens again during the day!

**Comment by JerseyEmerald** [comment]
Thank you for your help, upon further reading, I read my dailies history,, it showed 3/2 as the day my dailies had a few marked off but not the rest,  that's the same day I logged out because I got a new phone that very day... I also noticed in my dailies history that there were missing days, is that normal???
Again thank you for your help,  I'm m going to log out later in the day since it's 2:21 in the morning and I need some sleep lol but I'll screen shot it all and I will log out for several hours and will document what happens.

**Comment by JerseyEmerald** [comment]
Sorry I hit the wrong button....

**Comment by Alys** [comment]
@JerseyEmerald I've set up something that records your health and the streaks on your Dailies at regular intervals (not the names of the tasks or any other personal information) so that we can look into this in more detail if it happens again. If you notice any unexplained health loss or streaks changing incorrectly, or Dailies being marked as completed when they shouldn't be or vice versa, please tell us as soon as you can. If you're not able to comment on this issue, you can describe what you've seen in the Tavern and mention my name.

For missing days in your Dailies history, it depends on the details. Is this in the Data Display Tool? Or in the progress graph on the Habitica website? Could you show us a screenshot, if you don't mind? Was it for Dailies that are due every day and that you thought you had marked as completed every day?

**Comment by JerseyEmerald** [comment]
It's under the data display tool, dailies history, I have a screen shot. I always mark off my dailes and I even set an alert for 3 hours before midnight where I double check to make sure they're done.

**Comment by JerseyEmerald** [comment]
![screenshot_20160306-132711](https://cloud.githubusercontent.com/assets/17463902/13556203/a2295d42-e3a1-11e5-9cc6-c730e9b86bf5.png)
![screenshot_20160306-132756](https://cloud.githubusercontent.com/assets/17463902/13556206/a8cf311c-e3a1-11e5-8c58-7d3e0e22ba75.png)

**Comment by JerseyEmerald** [comment]
Thank you again, hope this helps.

**Comment by JerseyEmerald** [comment]
Ok, this is what I done so far
I took screen shots from data display tool
I completed a few dailies 
I logged off for 2 hrs both app and website
I logged back in after 7pm  browser and app
Everything looked the same 
I completed the rest of my dailies 
I went to data display tool,  verified dailes were marked completed 
I took a screen shot,  just in case
I will continue to monitor
Thank you again for your time

**Comment by Alys** [comment]
When you mark Dailies as complete but then discover later that they have been treated as if they weren't complete (e.g., from the x marks in the Data Display Tool), then it's generally a good sign that the bug I linked to has happened. The Habitica website had displayed your Dailies as completed but it had not sent that information to the server, and so when cron ran, cron treated the Dailies as not completed (causing the x marks in the DDT, and causing the streaks to be zero, and causing health loss).

Those x marks in the DDT can also happen if cron ran before you had time to complete your Dailies.

**Comment by JerseyEmerald** [comment]
That's why I compete my dailes before 8pm, cronies runs at 12 midnight, I recheck both the app and website...
Update: everything is working fine,  the daily tool showed 0 incomplete dailes, I think it's fixed
Thanks for your help ☺

**Comment by Alys** [comment]
There's a new report from @JerseyEmerald at https://github.com/HabitRPG/habitrpg/issues/6862

**Comment by Alys** [comment]
I'm closing this now because we'll continue it in HabitRPG/habitrpg#6862

There's a link from that issue back to this one so we can find this one again easily.
