### ISSUE TITLE
scrolling performance in rewards tab very slow

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#490]
The scrolling performance for the rewards tab is pretty bad. And apparently the issue also affects the todo tab (as the rewards tab is also loaded when the todo tab is selected)

**Comment by Redmega** [comment]
I've faced the same issue.

**Comment by dbarnett** [comment]
Habitica may actually be causing slowdowns for other apps as well, just by having Habitica active on the device, which is much worse.

I've been noticing a random but very frequent 1–2 second lag in other apps (Hangouts, email, etc.) on my phone, especially noticeable when I pull up the keyboard and try to type. I just uninstalled Habitica on a hunch and haven't been able to reproduce since then. I'll keep an eye on it and report  back if I start noticing it again without Habitica. For now it's worth just avoiding the app and using it through the website.

**Comment by thaleslessa** [comment]
Same occurs in Habits tab
