### ISSUE TITLE
Missing 2nd Triad bingo/reset cron caused streak reset/Orb of Rebirth, not able to choose class..

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitrpg-android#578]
My user ID 29c5340b-d150-4347-862c-fec571a18b8a
Using mobile Web browser  Android , Google Chrome, same on my computer 
 OK I have several issues
1. 2nd triad bingo not displayed under my achievements
     I released all pets and mounts first, recollected  pets, raised to mounts,collected pets again

2. Next problem, I reset my cron time for our team quest  so I could cron in with them. This caused my 
Dailes to appear not done and reset all my streaks .. I manually reset my streaks lekker to what they were

3. Same problem that I had before, 4 times to be exact, used ORB OF REBIRTH, went to choose a class
Like Mage, I couldn't select it, my cursor wouldn't go up to choose it.. I had same problem  3 times before
I had to exit out and go through the Wiki page that show a classes and choose it from there..this isn't the
Correct way to do this.  I should be able to choose from the menu when the Orb is used....

4. Loosing hp, resulting in my avatar death, when my dailes were completed 7 hours before cron..
My team was not on a quest of any kind...I  was reset back to level one, lost all my gold, 1 pc of equipment which really didn't bother me, I have plenty... this just really annoyed me considering I've not
Miss a single day since I started in January..

Any help would be greatly appreciated!!!  Thank you
Orb of Rebirth was an issue BEFORE the new update
The rest all just recently happened over past several  weeks

**Comment by Alys** [comment]
@JerseyEmerald I'm sorry about this! Much of this is because we don't seem to be describing Habitica's features well, so things that are actually features seem like bugs.

The Triad Bingo achievement is
https://guides.github.com/features/mastering-markdown/ gained when you release your pets and mounts, not when you collect them. If you use the Key to the Kennels a second time to release all your pets and mounts together, then the achievement text will change to "Has found all 90 pets, all 90 mounts, and found all 90 pets AGAIN (HOW DID YOU DO THAT!) and has released a full stable a total of 2 times".

Changing your Custom Day Start time can sometimes cause your cron to happen early on the day you change it. If you change it on the website, that can't happen unexpectedly because the website shows you a notification telling you the time that your cron will next run, and it lets you cancel the change if you decide that you can't finish all your Dailies by then. The mobile apps might not have that feature yet, but they will in future. Until then, if you need to change your Custom Day Start time, it's safest to do it on the website.

The Orb of Rebirth is actually not meant to let you change your class immediately. Instead, it's designed to make Habitica behave the same way that it does for a new player. That means that it sets your level back to 1, and then lets you unlock features one by one as you level up. For a new player, the ability to change class happens at level 10, and so after you've used the Orb of Rebirth, you also don't choose a new class until level 10.

This part does seem like a bug:
_"Loosing hp, resulting in my avatar death, when my dailes were completed 7 hours before cron.. My team was not on a quest of any kind...I was reset back to level one, lost all my gold, 1 pc of equipment"_
Can you tell me when that happened? If it was in the past day or two, we might be able to investigate it to work out what happened. If it was further in the past, then there might not be any data left that we can look at.

Habitica actually has an easier way to report bugs now, instead of posting to GitHub. From the Habitica website's menu, you can go to Help > Report a Bug. That takes you to a guild in Habitica and you can describe your problem there. The best part about it is that it's really quick to get there and post, so you can report a bug as soon as it happens. When we find out about bugs soon after they occur, we can usually get enough information to work out what went wrong. Unfortunately that's not always possible if bugs are reported a day or more after they happen.

Let me know if you have questions about any of this! If you want to keep discussing any of the things you've reported here, keep posting to this issue, but for any future bugs you find, you can use that "Help > Report a Bug" guild.

**Comment by JerseyEmerald** [comment]
Triad bingo.... is this correct to obtain this the first time, I collected pets, fed them, turned them into mounts and collected again... I got the triad bingo achievement 
So for me to get triad bingo this time, I need to release  the mounts??

The cron problem, I was on my website browser on my cell phone. I stopped using the mobile app since I could do a lot more this way. So I changed my cron time from the browser. This happened over a week ago and I fixed every thing.. it hasn't happened since . 

Orb of Rebirth... It gives you the option to choose change of class and when I reached level 10,I didn't have to choose a class. I'll be coming up to level 100 soon and will do screen shots..

**Comment by JerseyEmerald** [comment]
Thank you !!!

**Comment by Alys** [comment]
Actually, I was a bit wrong about the Triad Bingo achievement. It is given as soon as you've first collected all pets and mounts and pets again, and when you get it, the text on your Achievements page says "Has found all 90 pets, all 90 mounts, and found all 90 pets AGAIN (HOW DID YOU DO THAT!)". Then after that, if you use the Key to the Kennels, this additional text is added to the end: " and has released a full stable a total of 1 times". The number indicates how many times you've released pets and mounts. If you release them a second time, the number will increase to 2. So what you're seeing at the moment is correct since you've released pets and mounts only once so far.

I've just tested the Orb of Rebirth on a test account and it didn't give me the option to choose a class, instead it gave me the default Warrior class, which is what it should do. If the Orb does let you choose a class as soon as you use the Orb, please do tell us, because that's definitely a bug we would want to fix! You should still be able to choose a class at level 10 after using the Orb.

When you changed your custom day start time, there would have been a confirmation screen that told you when cron would next run. Do you remember what it said? If it didn't tell you the correct time, we would want to know!

**Comment by JerseyEmerald** [comment]
Ok Thank you for that. 
On the screen to change cron, it showed the correct time that I choose, which 8pm, my time zone stayed the same, it asked me to verify if it's correct, I said yes, then it told me the usual to make sure my dailes were done and showe'd correct time...

**Comment by Alys** [comment]
So it showed you the correct date and time that cron actually ran on? If not, do you remember the exact date and time it showed you and the time that cron ran next?

**Comment by JerseyEmerald** [comment]
To be honest, i didn't  pay attention to the date, I did this on July 3, I did my dailes early and reset my cron to any early time..I signed out when I went back in I noticed my streaks were reset to zero, daily log showed I didn't complete my dailes when I did...I fixed all that then a few days later, I was logged out for  7 hrs, I signed in and it showed I died, it was before cron so I was able to fix it so it didn't show up on the daily log

**Comment by Alys** [comment]
Thanks for the details!

If you do need to change your Custom Day Start time again, it's worth paying close attention to the date and time that it tells you, because that will let you know the earliest time that cron could run. If you know you can't complete your Dailies before then, you can cancel the Custom Day Start change, and make it again later after your Dailies are finished.

If you have any more problems with it, please contact us as soon as you can, by going to Help > Report a Bug from the website's menu. Unfortunately the events you're describing are too far in the past for us to be able to obtain information about what happened.
