### ISSUE TITLE
Tests for Android

### ISSUE THREAD

**Issue by franzejr** [HabitRPG/habitrpg-android#74]
This Application will have tests? Feature tests?

Probably https://github.com/robotiumtech/robotium is a good one idea.

**Comment by dlew** [comment]
Some information about testing...

Robotium is somewhat of an older project. Nowadays the recommended framework is Espresso (from Google). You can find out a lot more about that here: https://google.github.io/android-testing-support-library/

Generally speaking, the more unit tests you can have work without Android, the better (since pure Java unit tests are far faster). I'm not actually a big fan of integration tests because they're slow and brittle (any change to the UI can cause a problem). Testing the logic of the app quickly would be a good start.

Since the app is open source, you can use [Travis CI](https://travis-ci.org/) for free on it. The neat thing about that is that you can apply tests automatically to every pull request, which can act as a filter on bad PRs. For example, see RxBinding's current PRs, where one of them is currently failing to pass: https://github.com/JakeWharton/RxBinding/pull/128
